version: "3.9"
services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      API_URL: "http://localhost:${BACKEND_PORT}"
    volumes:
      - ./frontend/package.json:/usr/src/app/package.json:ro
      - ./frontend/package-lock.json:/usr/src/app/package-lock.json:rw
      - ./frontend/src:/usr/src/app/src:ro
      - ./typings:/usr/src/app/rm2-typings:ro

  backend:
    build:
      dockerfile: backend/Dockerfile 
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file: .env
    environment:
      PGHOST: db
    volumes:
      - ./backend/package.json:/usr/src/app/package.json:ro
      - ./backend/package-lock.json:/usr/src/app/package-lock.json:rw
      - ./backend/src:/usr/src/app/src:ro
      - ./backend/tests:/usr/src/app/tests:ro
      - ./backend/migrations_src:/usr/src/app/migrations_src:ro
      - ./backend/seeds:/usr/src/app/seeds:ro
      - ./typings:/usr/src/app/rm2-typings:ro

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 9091:8080
