version: "3.9"
services:
  web:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment: 
      PGHOST: db
      PGUSER: "${PGUSER}"
      PGDATABASE: "${PGDATABASE}"
      PGPASSWORD: "${PGPASSWORD}"
    volumes:
      - ./src:/usr/src/app/src:ro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080
