version: "3.9"
services:
  web:
    build: .
    ports:
      - "6627:6627"
    environment: 
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: example
    volumes:
      - ./src:/usr/src/app/src:ro

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080
