version: "3.9"
services:
  frontend:
    restart: unless-stopped
    build:
      context: frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      API_URL: "http://localhost:${BACKEND_PORT}"
    volumes:
      - ./frontend/src:/usr/src/app/src:ro

  backend:
    restart: unless-stopped
    build:
      context: backend
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file: .env
    environment:
      PG_HOST: db
    volumes:
      - ./backend/src:/usr/src/app/src:ro
      - ./backend/tests:/usr/src/app/tests:ro
      - ./backend/migrations_src:/usr/src/app/migrations_src:ro
      - ./backend/seeds:/usr/src/app/seeds:ro
      - ./.env.template:/usr/src/.env.template:ro

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9091:8080"
