FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm i

# Copy the rest
COPY . ./

EXPOSE 6627

# Just run dist server
# CMD ["npm", "run", "start"]

# Restart when file changes
CMD ["npm", "run", "watch"]

# DEBUG: Keep the container running for debugging purposes
# CMD ["tail", "-f", "/dev/null"]